services:
  app:
   build: .
   volumes:
     - .:/dj_test
   ports:
     - ${PORT}:8000
   image: app:dj_test
   container_name: dj_test_deploy
   command: gunicorn dj_test.wsgi:application --bind 0.0.0.0:8000
   env_file:
    - .env

  nginx:
    image: nginx:latest
    container_name: dj_nginx
    ports:
      - "80:80"  # Map port 50 on the host to port 50 on the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx configuration
      - ./mediafiles:/app/mediafiles  # Mount media files
    depends_on:
      - app
    expose:
      - 8000